#!/usr/bin/env python3
"""generate an HTML file from a YAML Snippets DB."""

import argparse

import yaml
import jinja2

from typing import Any, Dict, List, Union

# body{margin:40px auto;max-width:650px;line-height:1.6;font-size:18px;color:#444;padding:0 10px}h1,h2,h3{line-height:1.2}

TEMPLATE = '''
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>snippets</title>
    <style>
        :root {
                --background-color: white;
                --foreground-color: black;
                --accent-color:     grey;
        }
        @media (prefers-color-scheme: dark) {
            :root {
                --background-color: #1f1f1f;
                --foreground-color: #ddd;
            }
        }

        body {
                background: var(--background-color);
                color:      var(--foreground-color);
        }
        a, a:visited {
                color: var(--accent-color);
        }
        a:hover {
                color: var(--foreground-color);
        }

        h1,h2,h3 {
                line-height: 1.2;
        }

    </style>
</head>
<body>
    <main>
        {%- macro section(depth, path, name, snippets) -%}
        {%- with -%}
        {%- if depth == 1 -%}
            {%- set id = '' -%}
        {%- elif depth == 2 -%}
            {%- set id = name -%}
        {%- else -%}
            {%- set id = path ~ '/' ~ name -%}
        {%- endif -%}
            <section id='{{ id | urlencode }}'>
            <h{{ depth }}><a href='#{{ id | urlencode }}'>{{ name | escape }}</a></h{{ depth }}>
            {%- if snippets is string -%}
                <pre>{{ snippets | strip | escape }}</pre>
            {%- elif snippets is mapping -%}
                {%- for k, v in snippets.items() -%}
                    {{ section(depth + 1, id, k, v) }}
                {%- endfor %}
            {%- else -%}
                {%- for snippet in snippets -%}
                    <pre>{{ snippet | strip | escape }}</pre>
                {%- endfor -%}
            {%- endif -%}
            </section>
        {%- endwith -%}
        {%- endmacro -%}
        {{ section(1, '', 'Snippets', snippets) }}
    </main>
    <script type='module'>
    </script>
</body>
</html>
'''.strip()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--db', type=argparse.FileType('r'),
                        required=True, help='path to db.yaml')
    parser.add_argument('--output', type=argparse.FileType('w'),
                        required=True, help='path to output HTML')
    args = parser.parse_args()

    bytes = args.db.read()

    snippets = yaml.safe_load(bytes)

    environment = jinja2.Environment()
    environment.filters['strip'] = lambda s: s.strip()

    print(environment.from_string(TEMPLATE).render(
        snippets=snippets), file=args.output)
